<?php

   /*============================================================================*\  
   ||                               -= Drupaltin =-                              ||
   ||                                                                            ||
   || By Jordan Starcher                                                         ||
   || drupaltin.module -> /drupal/modules/drupaltin/                             ||
   || Engineered for Drupal 5.x & vB 3.6.x                                       ||
   || Project Version 5.x-1.0a                                                   ||
   || File Version 1.01                                                          ||
   || February 20, 2007                                                          ||
   || Release under the GPL license                                              ||
   ||                                                                            ||
   ||                              Copyright ©2007                               ||
   ||                       http://www.TheOverclocked.com                        ||
   \*============================================================================*/


/**
 * Implementation of hook_help()
 */
function drupalvb_help($section = 'admin/help#drupaltin') {
  switch ($section) {
    case 'admin/modules#description':
      return t("Integrates users from vBulletin into Drupal without sacrificing usability");
  }
}

/**
 * Implementation of hook_perm()
 */
function drupaltin_perm() {
  return array('view drupaltin login');
}

/**
 * Implementation of hook_block()
 */
function drupaltin_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
    if ($op == 'list') {
    $blocks[0] = array('info' => t('Drupaltin login form'),
      'weight' => 0, 'enabled' => 1, 'region' => 'left');
	return $blocks;
  }
    else if ($op == 'configure' && $delta == 0) {
    return $form;
  } 
  else if ($op == 'view') {
    switch($delta) {
      case 0:
        if (!$user->uid) {
          $block['subject'] = t('User login');
          $block['content'] = "PASTE HERE";
        }
        return $block;
	}
  }	
}


function drupaltin_logout() {
	header('Location: drupaltin_logout.php?do=logout');
}


/**
 * Implementation of hook_menu()
 */
function drupaltin_menu($may_cache) {
        global $user;
        if ($may_cache) {
 $items[] = array('path' => 'drupaltin_logout', 'title' => t('Log Out'),
      'callback' => 'drupaltin_logout',
      'access' => $user->uid, 'weight' => '10', 'type' => MENU_NORMAL_ITEM);
        }
        return $items;
} 
